camera:
  global_index: 0
  local_index: 1
  width: 1280
  height: 720

cup_detection:
  min_area: 500
  colors:
    green:
      cup_id: 0
      lower: [40, 50, 50]
      upper: [85, 255, 255]
    red:
      cup_id: 1
      lower1: [0, 70, 50]
      upper1: [10, 255, 255]
      lower2: [170, 70, 50]
      upper2: [180, 255, 255]
    blue:
      cup_id: 2
      lower: [90, 50, 50]
      upper: [130, 255, 255]

tracking:
  touch_threshold: 0.12
  default_last_touched_time: 999.0
  user_absence_threshold: 10.0
  time_near_threshold: 0.8
  motion_distance_threshold: 0.03
  stationary_motion_threshold: 0.01
  touch_count_used_threshold: 1

policy:
  confidence_threshold: 0.65
  recent_touch_threshold: 10.0
  cleanup_time_threshold: 30.0
  stationary_threshold: 3.0
  model_input_features:
    - x
    - y
    - hand_distance
    - last_touched_time
    - touch_count
    - moved_recently
    - distance_to_tray
    - user_present
    - user_absent_time
    - is_active_cup
    - time_near_cup
    - time_since_release
    - release_count
    - cup_motion_distance
    - stationary_time
    - was_moved
    - used_cup_candidate
    - idle_candidate
  preprocessing:
    hand_distance_clip_upper: 2.0
    last_touched_time_clip_upper: 60.0
    user_absent_time_clip_upper: 60.0
    time_near_cup_clip_upper: 30.0
    time_since_release_clip_upper: 60.0
    cup_motion_distance_clip_upper: 2.0
    stationary_time_clip_upper: 60.0

local_liquid_detection:
  roi:
    x: 0.35
    y: 0.25
    w: 0.30
    h: 0.35
  min_color_ratio: 0.05
  min_dark_ratio: 0.08
  liquid_colors:
    red:
      lower1: [0, 70, 50]
      upper1: [10, 255, 255]
      lower2: [170, 70, 50]
      upper2: [180, 255, 255]
    blue:
      lower: [90, 50, 50]
      upper: [130, 255, 255]
    orange:
      lower: [10, 70, 50]
      upper: [30, 255, 255]

robot:
  tray_position:
    x: 0.50
    y: 0.20
    z: 0.10
